"""Added location field to Event model

Revision ID: 6c3fd6f8e8b7
Revises: 35aa1ef70254
Create Date: 2024-07-10 10:25:36.209877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3fd6f8e8b7'
down_revision = '35aa1ef70254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
